/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

import Phone from '../../public/glb/Phone.glb';

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials} = useGLTF(Phone);
  return (
    <group ref={group} {...props} dispose={null} scale={0.15} position={[3.9, 0.4, 0.6]} rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.5}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.mobilePhone_PhoneMaterial_0.geometry}
            material={materials.PhoneMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(Phone);
